### ISSUE TITLE
Add support for block of code

### ISSUE THREAD

**Issue by ahangarha** [ahangarha/markdown-it-bidi#7]

**Comment by ahangarha** [comment]
Code block gets implemented like this:

```html
<pre><code>
the code
</code></pre>
```

Since code is `inline`, adding `dir="auto"` won't help. We need some css trick like this:

```css
pre > code {
    unicode-bidi: plaintext;
    text-align: start;
    display: block;
}
```
